// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxlOcrNY6DGfvcbTeR4UWf5s4AeC0FpsI',
    appId: '1:248449003723:web:648d473b341f8d0b772b4e',
    messagingSenderId: '248449003723',
    projectId: 'taller-01pf',
    authDomain: 'taller-01pf.firebaseapp.com',
    storageBucket: 'taller-01pf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAF59aKPznqi0lU0yZDDkGO14Akwp0VY',
    appId: '1:248449003723:android:a0207b54e0a3a8a4772b4e',
    messagingSenderId: '248449003723',
    projectId: 'taller-01pf',
    storageBucket: 'taller-01pf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3voiAyJDsFYKHr6azY9eYRxxZRdZGc3Y',
    appId: '1:248449003723:ios:651940520fc0b378772b4e',
    messagingSenderId: '248449003723',
    projectId: 'taller-01pf',
    storageBucket: 'taller-01pf.appspot.com',
    iosBundleId: 'com.example.taller01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3voiAyJDsFYKHr6azY9eYRxxZRdZGc3Y',
    appId: '1:248449003723:ios:651940520fc0b378772b4e',
    messagingSenderId: '248449003723',
    projectId: 'taller-01pf',
    storageBucket: 'taller-01pf.appspot.com',
    iosBundleId: 'com.example.taller01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxlOcrNY6DGfvcbTeR4UWf5s4AeC0FpsI',
    appId: '1:248449003723:web:8dcfb56a5820c494772b4e',
    messagingSenderId: '248449003723',
    projectId: 'taller-01pf',
    authDomain: 'taller-01pf.firebaseapp.com',
    storageBucket: 'taller-01pf.appspot.com',
  );
}
